site_name: My Wiki
theme:
  name: material
  font: false
  palette:
    scheme: slate
extra_css:
  - stylesheets/extra.css
copyright: "Lick-Wilmerding High School Department of Technical Arts"
extra:
  generator: false
